### ISSUE TITLE
[Bug] Bundle is not signed even when `enable-bundle-signing` is set to `true`

### ISSUE THREAD

**Issue by HEIGE-PCloud** [LanceMcCarthy/Action-MsixBundler#3]
This is reproduced in the development workflow of this repo as well.

See https://github.com/LanceMcCarthy/Action-MsixBundler/runs/4270178644?check_suite_focus=true

At step: Test 1! Bundling with Signing (and multiple inputs)

Bundle signing is not enabled, skipping signing.

**Comment by LanceMcCarthy** [comment]
Hi @HEIGE-PCloud I just published a new release 1.0.1 that contains the fix. Can you confirm if it is producing the signed bundle correctly? 

I've been seeing some funny behavior recently with WinUI3 msix bundles using SignTool in which Windows doesn't respect the certificate. 

> I also updated the v1 tag to point to the 1.0.1 release. so if your workflow is using the v1 tag, it will automatically use the 1.0.1 release.

**Comment by HEIGE-PCloud** [comment]
I can confirm that the package is signed correctly now.

```
Bundle creation succeeded.

Beginning code signing of msixbundle file.
Parameters validated, beginning signing...
Done Adding Additional Store
Successfully signed: src\Bundle\bundle.msixbundle

Signing complete!
```

And Windows does not seem to have any problem recognizing my self-signed certificate as well...

![IMG_1572](https://user-images.githubusercontent.com/52968553/148229324-429334c4-9a32-4932-9b6e-7325fbc810fa.JPG)

Everything is fine on my side... Thanks! =)

**Comment by LanceMcCarthy** [comment]
Fantastic!
